"""extend jobs with scraper fields

Revision ID: c55b7d98c4a4
Revises: 515b4ba10d3f
Create Date: 2025-10-16 08:48:37.944308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55b7d98c4a4'
down_revision: Union[str, Sequence[str], None] = '515b4ba10d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_type', sa.String(length=60), nullable=True))
    op.add_column('jobs', sa.Column('logo', sa.String(length=512), nullable=True))
    op.add_column('jobs', sa.Column('apply_url', sa.String(length=512), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('jobs', 'tech_stack',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('jobs', 'salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=60),
               existing_nullable=True)
    op.create_index(op.f('ix_jobs_company'), 'jobs', ['company'], unique=False)
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=False)
    op.create_index(op.f('ix_jobs_location'), 'jobs', ['location'], unique=False)
    op.create_index(op.f('ix_jobs_source'), 'jobs', ['source'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_index('ix_jobs_title_company', 'jobs', ['title', 'company'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_title_company', table_name='jobs')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_location'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_external_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company'), table_name='jobs')
    op.alter_column('jobs', 'salary',
               existing_type=sa.String(length=60),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('jobs', 'tech_stack',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'apply_url')
    op.drop_column('jobs', 'logo')
    op.drop_column('jobs', 'job_type')
    # ### end Alembic commands ###
